### ISSUE TITLE
Общие принципы взаимодействия

### ISSUE THREAD

**Issue by wldmr-key** [alex309706/Confectionery#6]
Почему ты не ставишь себе задачи на спринт и не взаимодействуешь по моим замечаниям?
Неужели ты считаешь, что мне удобно просматривать твои тексты и выискивать исправления?

Где начало работы над проектной частью и подготовка прототипа по плану?

**Comment by alex309706** [comment]
![image](https://user-images.githubusercontent.com/43037401/46879544-02d43500-ce4f-11e8-9971-465b38c86f15.png)
я почему-то думал, что "commit"ы тоже вам видны..том-то я и писал что делал

**Comment by alex309706** [comment]
![image](https://user-images.githubusercontent.com/43037401/46879721-72e2bb00-ce4f-11e8-9d26-de3fc833254d.png)
и это вам тоже не видно..понял

**Comment by wldmr-key** [comment]
нет, мне все видно. Но в историю коммитов я посмотреть не догадался )) (но ты молодец, что пишешь информативно, но, сам, понимаешь, что это для меня плохая лоция, если я смотрю на проект раз в неделю). Проект мне тоже виден, но я не могу по нему вспомнить (раз  в неделю) динамику.
Задачу же (и комментарии к ней)  я вижу сразу же и могу быстро прореагировать (могу и не быстро, но, как правило, это легче так как я решаю локальную проблему)

**Comment by alex309706** [comment]
хорошо...значит,исправления лучше выносить в 'issues' и описывать их тут..наличие прогрессбара обязательно?я что-то не разобрался как его поставить..выходные обещают пройти на славу)

**Comment by wldmr-key** [comment]
да, правильно. Прогрессбар необязателен
